name: Github actions test
on:
  push:
    branches:
      - master
jobs:
  IaC-change:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code from repo
         uses: actions/checkout@v3
       - name: Check changed file
         id: files
         uses: jitterbit/get-changed-files@v1
       - name: Check for changed files
         if: contains( steps.files.outputs.all, 'CloudFormation' )
         run: echo "Its an IaC change"
       - name: Identify env
         if: github.ref == 'refs/heads/master'
         run: echo "Current environment is test"
       - name: Check current directory and contents
         run: |
              pwd
              ls -la
       - name: Configure AWS credentials for deployment
         uses: aws-actions/configure-aws-credentials@v1
         with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 3600
       - name: Deploy to AWS CloudFormation
         uses: aws-actions/aws-cloudformation-github-deploy@v1
         with:
          name: TestEC2Stack
          template: CloudFormation/ec2.yml
