name: Github actions test
on:
  push:
    branches:
      - master
jobs:
  Checkout-code:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code from repo
         uses: actions/checkout@v3
  Identify-the-change:
     runs-on: ubuntu-latest
     outputs:
       all: ${{ steps.files.outputs.all }}
       added: ${{ steps.files.outputs.added }}
       modified: ${{ steps.files.outputs.modified }}
       removed: ${{ steps.files.outputs.removed }}
       renamed: ${{ steps.files.outputs.renamed }}
       added_modified: ${{ steps.files.outputs.added_modified }}
       deleted: ${{ steps.files.outputs.deleted }}
     steps:
       - name: Check files changed
         id: files
         uses: jitterbit/get-changed-files@v1
  IaC-change:
     runs-on: ubuntu-latest
     if: contains( ${{jobs.Identify-the-change.outputs.all}}, 'CloudFormation' )
     steps:     
       - name: Identify env
         if: github.ref == 'refs/heads/master'
         run: echo "Current environment is test"
       - name: Check current directory and contents
         run: |
              pwd
              ls -la
       - name: Configure AWS credentials for deployment
         uses: aws-actions/configure-aws-credentials@v1
         with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 3600
       - name: Queue message for change delegator in SQS
         uses: ./.github/actions/sqs-publish
         with:
           sqs-arn: ${{ secrets.SQS_ARN }}
           publish-message: "{Change-type: IaC,region:us-east-1,Changes: ${{ steps.files.outputs.all }}}"
           message-group-id: "us-east-1"
       - name: Trigger Deployment job 
         uses: ./.github/actions/jenkins-trigger
         with:
          jenkins_url: ${{ secrets.JENKINS_URL }}
          job_name: "githubactions-test"
          user_name: ${{ secrets.JENKINS_USER }}
          api_token: ${{ secrets.JENKINS_TOKEN }}
          timeout: "1000"
          parameters: '{"region":"us-east-1","stack_name":"EC2test"}'
