name: Github actions test
on:
  push:
    branches:
      - master
jobs:
  Identify-subscriber:
     runs-on: ubuntu-latest
     steps:
       - name: Check changed file
         id: files
         uses: jitterbit/get-changed-files@v1
       - name: Check for changed files
         if: contains( steps.files.outputs.all, 'CloudFormation' )
         run: echo "Its an IaC change"
       - name: Identify env
         if: github.ref == 'refs/heads/master'
         run: echo "Current environment is test"
       - name: Trigger Jenkins job
         uses: jabbukka/jenkins-trigger@main
         with:
          url: ${{ secrets.JENKINS_URL }}
          job_name: "githubactions-test"
          user_name: ${{ secrets.JENKINS_USER }}
          api_token: ${{ secrets.JENKINS_TOKEN }}
          wait: "true"
          timeout: "1000"
