name: Github actions test
on:
  push:
    branches:
      - master
jobs:
  Identify-subscriber:
     runs-on: ubuntu-latest
     steps:
       - name: Getting Github event
         run: echo '${{ toJSON(github) }}'
       - name: Identify env
         if: github.ref == 'refs/heads/master'
         run: echo "Current environment is test"
